config/routes.rb
Rails.application.routes.draw do
  root to: 'point_tracker#tracker'
  devise_for :members, controllers: { omniauth_callbacks: 'members/omniauth_callbacks' }
  devise_scope :member do
    get 'members/sign_in', to: 'members/sessions#new', as: :new_member_session
    get 'members/sign_out', to: 'members/sessions#destroy', as: :destroy_member_session
  end
  # root 'home#index'
  # service page
  get 'service_logger/new'
  get 'service_logger/index'
  get 'service_logger/edit'
  get 'service_logger/delete'
  get 'service_logger/show'

  resources :events do
    member do
      get :delete
      get :attend
      get :unattend
      get :toggle_lock
    end
  end

  # get 'events/attend'

  resources :services do
    member do
      get :delete
      post :approve
      post :unapprove
    end
  end

  resources :member

  resources :whitelists do
    member do
      get :delete
    end
  end

  get 'dashboard/index'
  get 'dashboard/properties'
  get 'dashboard/reports'
  # get 'admin/create_event'
  get 'tos' => 'info#tos'
  get 'privacy' => 'info#privacy'
  get 'help' => 'info#help'
  get 'home/index'
  get 'service_logger/new', to: 'service_logger#new'
  post 'service_logger/index', to: 'service_logger#create'
  get 'point_tracker/tracker'
  get 'point_tracker/admin'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord
  validates :hours, presence: true
  validates :date, presence: true
  validates :description, presence: true, length: { minimum: 3, maximum: 4095 }

  def format_date
    if date.nil?
      '--'
    else
      date.strftime('%m/%d/%Y')
    end
  end

  def approved_img_path
    if isApproved?
      'check.png'
    else
      'ex.png'
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @service_hours = nil
    @greeting = 'Your Logged Service Hours'
    if current_member.isAdmin == true
      @service_hours = Service.all.order('date desc')
      @service_hours_approved = Service.where(isApproved: true).limit(20).order('date asc')
      @service_hours_unapproved = Service.where(isApproved: false).limit(20).order('date asc')
      @greeting = 'All Service Hours'
    else
      @service_hours = Service.where(member_id: current_member.id).limit(20).order('date desc')

    end
  end

  def show
    @service = Service.find_by(id: params[:id])

    if @service.nil?
      flash[:not_found] = 'Not found'
      redirect_to(services_path)
    end
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    @service.member_id =  current_member.id
    @service.isApproved = false
    if @service.save
      redirect_to(services_path)
    else
      render('new')
    end
  end

  def edit
    @service = Service.find_by(id: params[:id])
    render('edit') if @service.nil?
  end

  def update
    @service = Service.find(params[:id])
    if @service.update(service_params)
      redirect_to(service_path(@service))
    else
      flash[:danger] = @service.errors.full_messages
      redirect_to edit_service_path
    end
  end

  def delete
    @service = Service.find(params[:id])
  end

  def destroy
    @service = Service.find(params[:id])
    @service.destroy
    redirect_to(services_path)
  end

  def approve
    @service = Service.find(params[:id])
    @service.update(isApproved: true)
    redirect_to(services_path)
  end

  def unapprove
    @service = Service.find(params[:id])
    @service.update(isApproved: false)
    redirect_to(services_path)
  end

  private

  def service_params
    params.require(:service).permit(:hours, :date, :description)
  end
end

app/views/services/_form.html.erb
<%= error_messages_for(f.object) %>

<div class="card mb-4 p-3">
  <div class="card-body" summary="Event form fields">
    <div class="mb-3">
      <%= f.label :hours, {class: "form-label"} %>
      <%= f.number_field :hours, {class: "form-control", value: 1} %>
    </div>

    <div class="mb-3">
      <%= f.label :description, {class: "form-label"} %>
      <%= f.text_area :description, {class: "form-control"} %>
    </div>
    
    <div class="row">
      <div class="col">
        <div class="mb-4">
          <%= f.label :date, {class: "form-label"} %>
          <%= f.date_field :date, {max: Date.today, class: "form-control", value: Date.today} %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/services/_table.html.erb
  <% if service_hours.length() == 0 %>
    <p>There are no service hours logged</p>
  <% else %>
  
  
  <table class="table table-striped" summary="Service list">
    <tr class="header">
      <th>Description</th>
      <th>Date</th>
      <th>Hours</th>      
      <th>Approved?</th>
      <th>Actions</th>
    </tr>
    <% service_hours.each do |service| %>
    <tr>
      <td><%= service.description %></td>
      <td><%= service.format_date %></td>
      <td><%= service.hours %></td>
      <td><%= image_tag service.approved_img_path, height: 30 %></td>
      

    <td>        
      <div><%= link_to("Details", service_path(service), :class => 'action show') %></div>
      <% if !service.isApproved %>
      <div><%= link_to("Edit", edit_service_path(service), :class => 'action edit') %></div>
      <div><%= link_to("Delete", delete_service_path(service), :class => 'action delete') %></div>
      <% end %>
    </td>
    </tr>
    <% end %>
    <% end %>
  </table>

app/views/services/_tableApproved.html.erb
<h2>Approved</h2>

<% if service_hours.length() == 0 %>
  <p>No Service Hours Approved</p>
<% else %>
  <table class="table table-striped" summary="Event list">
    <tr class="header">
      <th>Description</th>
      <th>Date</th>
      <th>Hours</th>
      <th>Submitted By</th> 
      <th>Approved?</th>
      <th>Actions</th>
    </tr>
    <% service_hours.each do |service| %>
      <tr>
        <td><%= service.description %></td>
        <td><%= service.format_date %></td>
        <td><%= service.hours %></td>
        <td>
        <% unless Member.find_by(id: service.member_id).nil? || Member.find_by(id: service.member_id) == 0 %>
          <%= Member.find_by(id: service.member_id).name %>
        <% end %>          
        </td>
        <td><%= image_tag service.approved_img_path, height: 30, alt: "approved checkmark", class: "check" %></td>
        <td>
          <div><%= button_to 'Unapprove', {:controller => "services", :class => "btn btn-primary", :action => "unapprove", :id => service.id}, {:method=>:post}%></div>
          <div><%= link_to("Details", service_path(service), :class => 'action show') %></div>
          <div><%= link_to("Edit", edit_service_path(service), :class => 'action edit') %></div>
          <div><%= link_to("Delete", delete_service_path(service), :class => 'action delete') %></div>
        </td>
      </tr>
    <% end %> 
  </table>
<% end %>

app/views/services/_tableUnapproved.html.erb
<h2>Not approved</h2>

<% if service_hours.length() == 0 %>
  <p>All Service Hours Approved!</p>
<% else %>
  <table class="table table-striped" summary="Event list">
    <tr class="header">
      <th>Description</th>
      <th>Date</th>
      <th>Hours</th>
      <th>Submitted By</th>      
      <th>Approved?</th>
      <th>Actions</th>
    </tr>
    <% service_hours.each do |service| %>
      <tr>
        <td><%= service.description %></td>
        <td><%= service.format_date %></td>
        <td><%= service.hours %></td>
        <td>
        <% unless Member.find_by(id: service.member_id).nil? || Member.find_by(id: service.member_id) == 0 %>
          <%= Member.find_by(id: service.member_id).name %>
        <% end %>
        </td>
        <td><%= image_tag service.approved_img_path, height: 30, alt: "unapproved x", class: "x"  %></td>
        <td>
          <div><%= button_to 'Approve', {:controller => "services", :class => "btn btn-primary", :action => "approve", :id => service.id}, {:method=>:post}%></div>
          <div><%= link_to("Details", service_path(service), :class => 'action show') %></div>
          <div><%= link_to("Edit", edit_service_path(service), :class => 'action edit') %></div>
          <div><%= link_to("Delete", delete_service_path(service), :class => 'action delete') %></div>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/services/delete.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div class="services edit" style="text-align:center">
    <h2>Delete Service Hour</h2>

    <%= form_for(@service, :method => 'delete') do |f| %>
      <p>Are you sure you want to permanently delete this service hour?</p>
      <div class="form-buttons ">
        <%= f.submit "DELETE", class: "btn btn-primary" %>
        <%= link_to("BACK", services_path, :class => 'back-link btn btn-primary') %>
      </div>
    <% end %>
  </div>
</body>
</html>

app/views/services/edit.html.erb
<!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Service</title>
  </head>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Archivo+Black&family=Montserrat:wght@700&display=swap');
    
    h2{
      font-family: 'Archivo Black', sans-serif;
      margin: 5rem auto;
      text-align: center;
    }

    .btn{
      font-family: 'Montserrat', sans-serif;
      font-weight: bold;
      margin-top: 5rem;
    }
    
    .card{
      margin: auto 5rem;
    }

    .form-buttons{
      text-align: center;
    }
    @media (max-width: 1000px) {
     .card {
       margin: auto 2rem;
     }
    
  }
  </style>
  <body>
    <div class="services edit">
      <h2>Edit Service</h2>
      <%= form_for(@service) do |f| %>
        <%= render(:partial => 'form', :locals => {:f => f}) %> 
        <div class="form-buttons">
          <%= f.submit "EDIT", class: "btn btn-primary" %>
          <%= link_to("BACK", services_path, :class => 'back-link btn btn-primary') %>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/services/index.html.erb
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Archivo+Black&family=Montserrat:wght@700&display=swap');

    .col{
      margin: 0 3rem;
    }

    h1{
      text-align: center;
      font-family: 'Archivo Black', sans-serif;
      margin: 5rem auto;
    }

    h2{
      font-family: 'Montserrat', sans-serif;
      margin-bottom: 5rem;
    }

    p{
      font-weight: 500;
    }

    th{
      text-align: center;
    }

    td{
      font-family: 'Montesserat', sans-serif;
    }

    .btn{
      font-family: 'Montserrat', sans-serif;
      font-weight: bold;
      margin-bottom: 0.5rem;
    }

    .container{
      font-family: 'Montserrat', sans-serif;
      margin: 10rem auto;
      text-align: center;
    }

    .form-buttons{
      text-align: center;
      margin-top: 5rem;
    }
    @media (max-width: 1000px) {
      .col{
        margin-right: 0rem;
      }
  
      .col{
        margin-left: 0rem;
      }

      h1{
      
      font-size: 8vw;
    }
    th{
      
      font-size: 2.2vw;
    }
    tr{
      font-size: 2vw;
    }
    
  }
  </style>

    <% content_for(:html_title) { 'Service' } %>
    <div class="mt-5 container services index">
      <h1><%= @greeting %></h1>

      <% if current_member.isAdmin %>
        <div class="row">
          <div class="col">
            <%= render :partial => 'tableUnapproved', locals: { service_hours: @service_hours_unapproved } %>
          </div>
          <div class="col">
            <%= render :partial => 'tableApproved', locals: { service_hours: @service_hours_approved } %>
          </div>
        </div>    
      <% else %>
        <%= render :partial => 'table', locals: { service_hours: @service_hours } %>
      <% end %>

      <% if !current_member.isAdmin %>
        <div class="form-buttons">
          <%= link_to("CREATE", new_service_path, :class => 'btn btn-primary action new') %>
        </div>
      <% end %>
    </div>

app/views/services/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Archivo+Black&family=Montserrat:wght@700&display=swap');

    .form-buttons{
      margin-top: 5rem;
      text-align: center;
    }

    .service.new{
      margin: 10%;
    }

    h1{
      text-align: center;
      font-family: 'Archivo Black', sans-serif;
      margin: 5rem auto;
    }

    .btn{
      font-family: 'Montserrat', sans-serif;
      font-weight: bold;
      margin-bottom: 0.5rem;
    }
  </style>
  <body>
    <% content_for(:html_title) { 'Create Service' } %>
    
    <div class="service new">
      <h1>Create Service</h1>
      <%= form_for(@service, :url => services_path, :method => 'post') do |f| %>
        <%= render(:partial => 'form', :locals => {:f => f}) %>
        <div class="mx-3 form-buttons">
          <%= f.submit "CREATE", class: "btn btn-primary" %>
          <%= link_to("BACK", services_path, :class => 'back-link btn btn-primary') %>
        </div>
      <% end %>
    </div>
  </body>
</html>

app/views/services/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Archivo+Black&family=Montserrat:wght@700&display=swap');
    
    h1{
      font-family: 'Archivo Black', sans-serif;
      text-align: center;
      margin-bottom: 5rem;
    }

    .button-group{
      margin-top: 5rem;
      text-align: center;
    }

    .service{
      text-align: left;
      margin: 10%;
    }

    .table-name{
      font-family: 'Archivo Black', sans-serif;
      text-align: center;
    }

    .btn{
      font-family: 'Montserrat', sans-serif;
      width: 10rem;
      margin-bottom: 0.5rem;
      text-align: center;
    }
  </style>
  <body>
    <div class="service show">
      <h1 class="table-name">Show Service</h1>
      <table class="table table-striped" summary="Service detail view">
        <tr>
          <th>Hours</th>
          <td><%= @service.hours %></td> 
        </tr>
        <tr>
          <th>Description</th>
          <td><%= @service.description %></td>
        </tr>
        <tr>
          <th>Date</th>
          <td><%= @service.format_date %></td>
        </tr>
        <tr>
          <th>Approved?</th>
          <td>
            <% if @service.isApproved %>
              <%= image_tag @service.approved_img_path, height: 30 %>
            <% else %>
              <%= image_tag @service.approved_img_path, height: 30 %>
            <% end %>
          </td>
        </tr>
      </table>
      <p class="button-group">
      <% if !current_member.isAdmin && !@service.isApproved %>        
          <%= link_to("EDIT", edit_service_path(@service), :class => 'action edit btn btn-primary') %>
          <%= link_to("DELETE", delete_service_path(@service), :class => 'action delete btn btn-primary') %>     
      <% end %>
      <%= link_to("BACK", services_path, :class => 'back-link btn btn-primary') %>
      </p>        
    </div>
  </body>
</html>

    