config/routes.rb
Rails.application.routes.draw do
  root to: 'point_tracker#tracker'
  devise_for :members, controllers: { omniauth_callbacks: 'members/omniauth_callbacks' }
  devise_scope :member do
    get 'members/sign_in', to: 'members/sessions#new', as: :new_member_session
    get 'members/sign_out', to: 'members/sessions#destroy', as: :destroy_member_session
  end
  # root 'home#index'
  # service page
  get 'service_logger/new'
  get 'service_logger/index'
  get 'service_logger/edit'
  get 'service_logger/delete'
  get 'service_logger/show'

  resources :events do
    member do
      get :delete
      get :attend
      get :unattend
      get :toggle_lock
    end
  end

  # get 'events/attend'

  resources :services do
    member do
      get :delete
      post :approve
      post :unapprove
    end
  end

  resources :member

  resources :whitelists do
    member do
      get :delete
    end
  end

  get 'dashboard/index'
  get 'dashboard/properties'
  get 'dashboard/reports'
  # get 'admin/create_event'
  get 'tos' => 'info#tos'
  get 'privacy' => 'info#privacy'
  get 'help' => 'info#help'
  get 'home/index'
  get 'service_logger/new', to: 'service_logger#new'
  post 'service_logger/index', to: 'service_logger#create'
  get 'point_tracker/tracker'
  get 'point_tracker/admin'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/whitelist.rb
class Whitelist < ApplicationRecord
end

app/controllers/whitelists_controller.rb
class WhitelistsController < ApplicationController
  def index
    redirect_to root_path if current_member.isAdmin == false
    @users = Whitelist.all
  end

  def new
    redirect_to root_path if current_member.isAdmin == false
    @user = Whitelist.new
  end

  def create
    redirect_to root_path if current_member.isAdmin == false
    @user = Whitelist.new(whitelist_params)
    if @user.save
      redirect_to(whitelists_path)
    else
      render('new')
    end
  end

  def edit
    redirect_to root_path if current_member.isAdmin == false
    @user = Whitelist.find_by(id: params[:id])
    render('edit') if @user.nil?
  end

  def update
    redirect_to root_path if current_member.isAdmin == false
    @user = Whitelist.find(params[:id])
    if @user.update(whitelist_params)
      redirect_to(whitelist_path(@user))
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to edit_whitelist_path
    end
  end

  def delete
    redirect_to root_path if current_member.isAdmin == false
    @user = Whitelist.find(params[:id])
  end

  def destroy
    redirect_to root_path if current_member.isAdmin == false
    @user = Whitelist.find(params[:id])
    @user.destroy
    redirect_to(whitelists_path)
  end

  private

  def whitelist_params
    params.require(:whitelist).permit(:email, :isAdmin)
  end
end

app/views/whitelists/_form.html.erb
    <%= error_messages_for(f.object) %>


    
    <div class="card mb-4 p-3">
        <div class="card-body" summary="Event form fields">
          <div class="mb-3">
            <%= f.label :email, {class: "form-label"} %>
            <%= f.text_field :email, {class: "form-control", required: true} %>
          </div>
        </div>
    </div>


  

app/views/whitelists/_table.html.erb
<table class="table table-striped" summary="Whitelist">
  <tr>
    <th>Email</th>
    <th>Actions</th>
  </tr>
  <% users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td>
        <div><%= link_to("Delete", delete_whitelist_path(user), :class => 'action delete') %></div>
      </td>
    </tr>
  <% end %>
</table>

app/views/whitelists/delete.html.erb
<%= link_to("<< Back to List", whitelists_path, :class => 'back-link') %>

<div class="whitelist edit">
  <h2>Delete User</h2>

  <%= form_for(@user, :method => 'delete') do |f| %>
    <p>Are you sure you want to permanently delete this user?</p>
    <div class="form-buttons">
      <%= f.submit("Delete User") %>
    </div>

  <% end %>
</div>

app/views/whitelists/edit.html.erb
<%= link_to("<< Back to List", whitelists_path, :class => 'back-link') %>

<div class="whitelists container edit">
  <h2>Edit User</h2>

  <%= form_for(@user) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit "Edit User", class: "btn btn-primary" %>
    </div>

  <% end %>
</div>

app/views/whitelists/index.html.erb
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Archivo+Black&family=Montserrat:wght@700&display=swap');

    h1{
      font-family: 'Archivo Black', sans-serif;
      text-align: center;
      margin-bottom: 5rem;
    }

    .form-buttons{
      font-family: 'Montserrat', sans-serif;
      font-weight: bold;
      margin-top: 5rem;
      text-align: center;
    }
  </style>
    <div class="mt-5 container whitelists index">
      <h1>Whitelisted Users</h1>
      <%= render :partial => 'table', locals: { users: @users, attended: true } %>
      <div class="form-buttons">
        <%= link_to("Add New User", new_whitelist_path, :class => "btn btn-primary action new") %>
      </div>
    </div>    

app/views/whitelists/new.html.erb
<% content_for(:html_title) { 'Whitelist User' } %>

<%= link_to("<< Back to List", whitelists_path, :class => 'back-link') %>


<div class="whitelists container new">
  <h2>Whitelist User</h2>

  <%= form_for(@user, :url => whitelists_path, :method => 'post') do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="mx-3 form-buttons">
      <%= f.submit "Whitelist User", class: "btn btn-primary" %>
    </div>

  <% end %>
</div>