config/routes.rb
Rails.application.routes.draw do
  root to: 'point_tracker#tracker'
  devise_for :members, controllers: { omniauth_callbacks: 'members/omniauth_callbacks' }
  devise_scope :member do
    get 'members/sign_in', to: 'members/sessions#new', as: :new_member_session
    get 'members/sign_out', to: 'members/sessions#destroy', as: :destroy_member_session
  end
  # root 'home#index'
  # service page
  get 'service_logger/new'
  get 'service_logger/index'
  get 'service_logger/edit'
  get 'service_logger/delete'
  get 'service_logger/show'

  resources :events do
    member do
      get :delete
      get :attend
      get :unattend
      get :toggle_lock
    end
  end

  # get 'events/attend'

  resources :services do
    member do
      get :delete
      post :approve
      post :unapprove
    end
  end

  resources :member

  resources :whitelists do
    member do
      get :delete
    end
  end

  get 'dashboard/index'
  get 'dashboard/properties'
  get 'dashboard/reports'
  # get 'admin/create_event'
  get 'tos' => 'info#tos'
  get 'privacy' => 'info#privacy'
  get 'help' => 'info#help'
  get 'home/index'
  get 'service_logger/new', to: 'service_logger#new'
  post 'service_logger/index', to: 'service_logger#create'
  get 'point_tracker/tracker'
  get 'point_tracker/admin'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 255 }
  validates :description, presence: true, length: { minimum: 3, maximum: 4095 }
  has_and_belongs_to_many :members

  def format_date
    if datetime.nil?
      '--'
    else
      datetime.strftime('%m/%d/%Y')
    end
  end

  def formatTime
    if datetime.nil?
      '--'
    else
      datetime.strftime('%I:%M %p')
    end
  end

  def formatted
    time.strftime('%H:%M') unless datetime.nil?
  end

  def createDateTime
    if !time.nil? and !date.nil?
      time.change(usec: 0)
      event_date = date
      event_time = time.change(year: event_date.year, month: event_date.month,
                               day: event_date.day)
      self.datetime = event_time
    end
  end

  def formatName
    name.truncate(30)
  end

  def to_s
    "Name:'#{name}' Description:'#{description}' Location: '#{location}'
    Datetime '#{datetime}' (Date '#{date}' Time '#{time}')"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @my_events = current_member.events

    ordered = Event.order(:datetime)

    @upcoming_events = ordered.where('datetime > ? or datetime IS NULL', Time.now).reject do |w|
      @my_events.include? w
    end
    @past_events = ordered.where('datetime <= ?', Time.now).reject { |w| @my_events.include? w }
  end

  def show
    @event = Event.find_by_id(params[:id])
    if @event.nil?
      flash[:not_found] = 'Not found'
      redirect_to(events_path)
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.time.nil? ^ @event.date.nil?
      flash[:danger] = ['Please enter both a day and time, or enter neither.']
      render(new_event_path)
      return
    end

    @event.createDateTime

    if @event.save
      redirect_to(events_path)
    else
      render('new')
    end
  end

  def edit
    @event = Event.find_by_id(params[:id])
    render('edit') if @event.nil?
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    @event.date = params[:event][:date]
    @event.time = params[:event][:time]

    if @event.time.nil? ^ @event.date.nil?
      flash[:danger] = ['Please enter both a day and time, or enter neither.']
      render(new_event_path)
      return
    end

    @event.createDateTime

    if @event.save
      redirect_to(event_path(@event))
    else
      flash[:danger] = @event.errors.full_messages
      redirect_to edit_event_path
    end
  end

  def delete
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to(events_path)
  end

  def attend
    @event = Event.find(params[:id])
    current_member.events << @event
    current_member.save
    redirect_to(events_path)
  end

  def unattend
    @event = Event.find(params[:id])
    current_member.events.delete(@event)
    current_member.save
    redirect_to(events_path)
  end

  def toggle_lock
    @event = Event.find(params[:id])
    @event.isLocked = !@event.isLocked
    flash[:danger] = @event.errors.full_messages unless @event.save
    redirect_to(events_path)
  end

  private

  def event_params
    params.require(:event).permit(:name, :description, :date, :isMandatory, :time, :location)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= error_messages_for(f.object) %>

<div class="card mb-4 p-3">
  <div class="card-body" summary="Event form fields">
    <div class="mb-3">
      <%= f.label :name, {class: "form-label"} %>
      <%= f.text_field :name, {class: "form-control", placeholder: "Provide a short name for this event...", required: true} %>
    </div>

    <div class="mb-3">
      <%= f.label :description, {class: "form-label"} %>
      <%= f.text_area :description, {class: "form-control", placeholder: "Include any details about the event here...", required: true} %>
    </div>

    <div class="mb-4">
      <%= f.label :location, {class: "form-label"} %>
      <%= f.text_field :location, {class: "form-control", placeholder: "Set a location for this event..."} %>
    </div>

    <div class="row">
      <div class="col">
        <div class="mb-4">
          <%= f.label :date, {class: "form-label"} %>
          <%= f.date_field :date, {class: "form-control", value: Date.today} %>
        </div>
      </div>

      <div class="col">
        <div class="mb-4">
          <%= f.label :time, {class: "form-label"} %>
          <%= f.time_field :time, {class: "form-control"}%>
        </div>
      </div>
    </div>

    <div class="mb-2">
      <%= f.label "Make Mandatory", {class: "form-label"} %>
      <%= f.check_box :isMandatory, {class: "form-check-label"} %>
    </div>
  </div>
</div>

app/views/events/_table.html.erb
<% if events.length() == 0 %>
  <p>There are no events here</p>
<% else %>
  <table class="table table-striped" summary="Event list">
    <tr>      
      <th>Event</th>
      <th>Description</th>
      <th>Location</th>
      <th>Is Mandatory</th>
      <th>Attendees</th>
      <th>Date</th>
      <th>Time</th>
      <% if current_member.isAdmin %>
      <th>Lock</th>
      <% end %>
      <th>Action</th>
    </tr>
    <% events.each do |event| %>
      <tr class="<%= event.isLocked ? 'reactive_color_red' : '' %>">        
        <td><%= event.formatName %></td>
        <td class="text-break"><%= event.description %></td>
        <td><%= event.location %></td>
        <td class="center"><%= event.isMandatory ? 'Yes' : 'No' %></td>
        <td><%=event.members.count%></td>
        <td><%= event.format_date %></td>
        <td><%= event.formatTime %></td>
        <% if current_member.isAdmin %>
          <% if event.isLocked %>
            <td><div><%= link_to("Unlock", toggle_lock_event_path(event), :class => 'action show') %></div></td>
          <% else %>
            <td><div><%= link_to("Lock", toggle_lock_event_path(event), :class => 'action show') %></div></td>
          <% end %>
        <% end %>
        <td>
          <% if !current_member.isAdmin %>
            <% if !event.isLocked %>
              <% if attended %>
                <div><%= link_to("Unattend", unattend_event_path(event), :class => 'action show') %></div>
              <% else %>
                <div><%= link_to("Attend", attend_event_path(event), :class => 'action show') %></div>
              <% end %>
            <% end %>         
          <% end %>          
          <div><%= link_to("Details", event_path(event), :class => 'action show') %></div>
          <% if current_member.isAdmin %>            
            <div><%= link_to("Edit", edit_event_path(event), :class => 'action edit') %></div>
            <div><%= link_to("Delete", delete_event_path(event), :class => 'action delete') %></div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/events/delete.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<style>
  .btn{
    font-family: 'Montserrat', sans-serif;
    font-weight: bold;
  }
</style>
<body>
  <div class="events edit" style="text-align:center">
    <h2>Delete Event</h2>

    <%= form_for(@event, :method => 'delete') do |f| %>
      <p>Are you sure you want to permanently delete this event?</p>
      <div class="form-buttons">
        <%= f.submit "DELETE", class: "btn btn-primary" %>
        <%= link_to("BACK", events_path, :class => 'back-link btn btn-primary') %>
      </div>

    <% end %>
  </div>
</body>
</html>

app/views/events/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Edit Event</title>
</head>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Archivo+Black&family=Montserrat:wght@700&display=swap');
    
    h2{
      font-family: 'Archivo Black', sans-serif;
      margin: 5rem auto;
      text-align: center;
    }

    .btn{
      font-family: 'Montserrat', sans-serif;
      font-weight: bold;
      margin-top: 5rem;
    }

    .form-buttons{
      text-align: center;
    }
</style>
<body>
  <div class="events container edit">
    <h2>Edit Event</h2>
    <%= form_for(@event) do |f| %>
      <%= render(:partial => 'form', :locals => {:f => f}) %>
      <div class="form-buttons">
        <%= f.submit "EDIT", class: "btn btn-primary" %>
        <%= link_to("BACK", events_path, :class => 'back-link btn btn-primary') %>
      </div>
    <% end %>
  </div>
</body>
</html>

app/views/events/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Archivo+Black&family=Montserrat:wght@700&display=swap');

    hr{
      margin: 2rem auto;
    }

    h1{
      font-family: 'Archivo Black', sans-serif;
      text-align: center;
      margin-bottom: 2rem;
    }

    h2{
      font-family: 'Montserrat', sans-serif;
      margin: 1rem auto;
    }

    p{
      font-weight: 500;
    }

    th{
      text-align: center;
    }

    td{
      font-family: 'Montesserat', sans-serif;
    }
    
    .btn{
      font-family: 'Montserrat', sans-serif;
      font-weight: bold;
      margin-top: 2rem;
    }

    .container{
      font-family: 'Montserrat', sans-serif;
      text-align: center;
    }

    .form-buttons{
      text-align: center;
    }
    @media (max-width: 1000px) {
      .col{
        margin-right: 0rem;
      }
  
      .col{
        margin-left: 0rem;
      }

      h1{
      
      font-size: 8vw;
    }
    th{
      
      font-size: 2vw;
    }
    tr{
      font-size: 2vw;
    }
    .table>:not(caption)>*>*{
      padding: 0.1rem 0.1rem;
    }
    h1 {
      margin: 1rem;
    }
    h2 {
      margin: 1rem;
    }
    
  }
  </style>
  <body>
    <% content_for(:html_title) { 'Events' } %>
    <%# container events index %>
    
      <div class="container mt-5 mb-5 events show">
      <h1>All Events</h1>
        <div class="row">
          <div class="col left">
            <table class="table table-striped" summary="Event detail view">
              <h2>Upcoming</h2>
              <%= render :partial => 'table', locals: { events: @upcoming_events, attended: false } %>
            </table>
          </div>
          <div class="col right">
            <table class="table table-striped" summary="Event detail view">
              <h2>Past</h2>
              <%= render :partial => 'table', locals: { events: @past_events, attended: false } %>
            </table>
          </div>
        </div>
      </div>

      <div class="container mt-5 ">
      <% if !current_member.isAdmin %>
        <h1>Attended Events</h1>
        <br>
        <%= render :partial => 'table', locals: { events: @my_events, attended: true } %>
        <hr>
      <% end %>
    </div>

    <% if current_member.isAdmin %>
        <div class="form-buttons">
          <%= link_to("CREATE", new_event_path, :class => 'btn btn-primary action new') %>
        </div>
      <% end %>
  </body>
</html>

app/views/events/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Archivo+Black&family=Montserrat:wght@700&display=swap');

    h2{
      font-family: 'Montserrat', sans-serif;
      text-align: center;
      margin-bottom: 5rem;
    }

    .btn{
      font-family: 'Montserrat', sans-serif;
      font-weight: bold;
      margin-top: 5rem;
    }

    .container{
      font-family: 'Montserrat', sans-serif;
    }
  </style>
  <body>
    <% content_for(:html_title) { 'Create Event' } %>
    
    <div class="events container new">
      <h2>Create Event</h2>
      <%= form_for(@event, :url => events_path, :method => 'post') do |f| %>
        <%= render(:partial => 'form', :locals => {:f => f}) %>
        <div class="mx-3 form-buttons">
          <%= f.submit "CREATE", class: "btn btn-primary" %>
          <%= link_to("BACK", events_path, :class => 'back-link btn btn-primary') %>
        </div>
      <% end %>
    </div>  
  </body>
</html>

app/views/events/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
  </head>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap');

    h2{
      font-family: 'Montserrat', sans-serif;
      text-align: center;
      margin-bottom: 5rem;
    }

    .btn{
      font-family: 'Montserrat', sans-serif;
      font-weight: bold;
      margin-top: 5rem;
    }

    .container{
      font-family: 'Montserrat', sans-serif;
      margin-top: 10rem;
    }

    .col.right{
      margin: 0 10rem;
    }

    .form-buttons{
      text-align: center;
    }
  </style>
  <body>
    <div class="container mt-5 events show">
      <div class="row">
        <div class="col">
          <h2 class="table-name">Event Info</h2>
          <table class="table table-striped" summary="Event detail view">
            <tr>
              <th>Name</th>
              <td><%= @event.name %></td>
            </tr>
            <tr>
              <th>Description</th>
              <td><%= @event.description %></td>
            </tr>
            <tr>
              <th>Location</th>
              <td><%= @event.location %></td>
            </tr>
            <tr>
              <th>Date</th>
              <td><%= @event.format_date %></td>
            </tr>
            <tr>
              <th>Time</th>
              <td><%= @event.formatTime %></td>
            </tr>
            <tr>
              <th>Mandatory? </th>
              <td><%= @event.isMandatory ? 'true' : 'false' %></td>
            </tr>
            <tr>
              <th>Created</th>
              <td><%= @event.created_at.strftime("%I:%M %P %B %-m, %Y") %></td>
            </tr>
            <tr>
              <th>Updated</th>
              <td><%= @event.updated_at.strftime("%I:%M %P %B %-m, %Y") %></td>
            </tr>
          </table>
        </div>
        <div class="col right">
          <table class="table table-striped" summary="Event list">
            <h2 class="table-name">Attendees</h2>
            <thead>
            </thead>
              <th>Name</th>
              <th>Email ID</th>
            <thead>
            <tbody>
              <% @event.members.each do |member| %>
                <tr>
                  <td><%= member.name %></td>
                  <td><%= member.email %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
      
        <div class="form-buttons">
          <p>
            <% if current_member.isAdmin %>
            <%= link_to("EDIT", edit_event_path(@event), :class => 'action edit btn btn-primary') %>
            <%= link_to("DELETE", delete_event_path(@event), :class => 'action delete btn btn-primary') %>
            <% end %>
            <%= link_to("BACK", events_path, :class => 'back-link btn btn-primary') %>
          </p>
        </div>
      
    </div>
  </body>
</html>