config/routes.rb
Rails.application.routes.draw do
  root to: 'point_tracker#tracker'
  devise_for :members, controllers: { omniauth_callbacks: 'members/omniauth_callbacks' }
  devise_scope :member do
    get 'members/sign_in', to: 'members/sessions#new', as: :new_member_session
    get 'members/sign_out', to: 'members/sessions#destroy', as: :destroy_member_session
  end
  # root 'home#index'
  # service page
  get 'service_logger/new'
  get 'service_logger/index'
  get 'service_logger/edit'
  get 'service_logger/delete'
  get 'service_logger/show'

  resources :events do
    member do
      get :delete
      get :attend
      get :unattend
      get :toggle_lock
    end
  end

  # get 'events/attend'

  resources :services do
    member do
      get :delete
      post :approve
      post :unapprove
    end
  end

  resources :member

  resources :whitelists do
    member do
      get :delete
    end
  end

  get 'dashboard/index'
  get 'dashboard/properties'
  get 'dashboard/reports'
  # get 'admin/create_event'
  get 'tos' => 'info#tos'
  get 'privacy' => 'info#privacy'
  get 'help' => 'info#help'
  get 'home/index'
  get 'service_logger/new', to: 'service_logger#new'
  post 'service_logger/index', to: 'service_logger#create'
  get 'point_tracker/tracker'
  get 'point_tracker/admin'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
    <footer class="mt-auto container-footer">
        <div style="max-width: 100%; overflow-x: hidden;">
            <div class="row justify-content-center mb-0 pt-5 pb-0 row-2 ps-3">
                <div class="col-12">
                    <div class="row row-2">
                        <div class="col-sm-3 text-md-center">
                            <h5><span> <i class="fa fa-firefox text-light" aria-hidden="true"></i></span><b></b></h5>
                        </div>
                        <div class="col-sm-3 my-sm-0 mt-5">
                            <ul class="nav">
                                <li class="mt-0">
                                     <%= link_to "Terms of Service", tos_path, class: "nav-link"  %>
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-3 my-sm-0 mt-5">
                            <ul class="nav">
                                <li class="mt-0">
                                <%= link_to "Privacy and Policy", privacy_path, class: "nav-link"  %>
                                </li>
                            </ul>
                        </div>
                        <div class="col-sm-3 my-sm-0 mt-5">
                            <ul class="nav">
                                <li class="mt-0">
                                     <%= link_to "Help", help_path, class: "nav-link"  %>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center mt-0 pt-0 row-1 mb-0 ps-sm-3 ps-2">
                <div class="col-12">
                    <div class="row my-4 row-1 no-gutters">
                        <div class="col-sm-3 col-auto text-center"><small>&#9400; Century Mens Society</small></div>
                        <div class="col-md-3 col-auto "></div>
                        <div class="col-md-3 col-auto"></div>
                        <div class="col my-auto text-md-left text-right "> <small> centuries-points-tracker.herokuapp.com <span><img src="https://i.imgur.com/TtB6MDc.png" class="img-fluid " width="25"></span> <span><img src="https://i.imgur.com/N90KDYM.png" class="img-fluid " width="25"></span></small> </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

app/views/layouts/_navbar.html.erb
<nav class="ml-2 navbar navbar-dark bg-dark navbar-expand-md" style="padding: 0;">
  <a class="navbar-brand" href="/">Century Mens Society</a>
  <button class="navbar-toggler" type="button"  data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
  <div class="navbar-collapse collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Service Hours", services_path, class: "nav-link"  %>
      </li>
      <li class="nav-item">
        <%= link_to "Events", events_path, class: "nav-link"  %>
      </li>
      <% if current_member.isAdmin? %>
        <li class="nav-item">
          <%= link_to "Whitelist", whitelists_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Members", member_index_path, class: "nav-link"  %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Sign Out", destroy_member_session_path, class: "nav-link"  %>
      </li>
      
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css"></link>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        
    <title><%= content_for?(:html_title) ? yield(:html_title) : "Default" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <style>
      .flash__alert   { color: red; }
      .flash__notice  { color: blue; }
      .flash__success { color: green; }
    </style>
  </head>

  <body class="d-flex flex-column min-vh-100">
    <%= render 'layouts/navbar' %>

    <% if flash.any? %>
      <% flash.each do |key, value| -%>
        <% if value.instance_of? Array %>
          <% value.each do |sub_value| -%>
            <section class="alert alert-<%= key %>"><%= sub_value %></section>
          <% end %>
        <% else %>
          <section class="alert alert-<%= key %>"><%= value.html_safe %></section>
        <% end %>
      <% end -%>
    <% end %>
    <div class="mb-3"><%= yield %></div>
    <%= render 'layouts/footer' %>
  </body>
</html>